import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Navbar from "@/components/Navbar"
import { CartProvider } from "@/components/CartContext";
import BottomNavbar from "@/components/BottomNavbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <CartProvider>
            <Navbar></Navbar>
            <div className="pt-16 pb-[64px] lg:pb-0">
              {children}
            </div>
            <BottomNavbar></BottomNavbar>
          </CartProvider>
        </SessionProvider>
      </body>
    </html>
  );
}